require("theGarchomp.set")
require("theGarchomp.packer")
require("theGarchomp.color")
require("theGarchomp.keymaps")
require("theGarchomp.remaps")
require("theGarchomp.neogit")
require("theGarchomp.clipboard")
require("theGarchomp.vimWiki")
